name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT: alpine-keep-440111-r4
  IMAGE_NAME: cicd2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_KEY_COBA }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/${{ env.GCP_PROJECT }}/${{ env.IMAGE_NAME }}:latest
      
       - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.SERVICE }} \
            --image gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.IMAGE_NAME }}:latest \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --service-account=848793158287-compute@developer.gserviceaccount.com
