name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

 
      - name: Set Up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with: 
            project_id: ${{ secrets.PROJECT_ID }}
            service_account_key: ${{ secrets.GCP_KEY_COBA }}


      # - name: Create .env file
      #   run: |
      #     echo PORT=${{ secrets.PORT }} >> .env
      #     echo BUCKET_NAME=${{ secrets.BUCKET_NAME }} >> .env
      #     echo DB_DIALECT=${{ secrets.DB_DIALECT }} >> .env
      #     echo DB_HOST=${{ secrets.DB_HOST }} >> .env
      #     echo DB_NAME=${{ secrets.DB_NAME }} >> .env
      #     echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
      #     echo DB_SOCKET_PATH=${{ secrets.DB_SOCKET_PATH }} >> .env
      #     echo DB_USER=${{ secrets.DB_USER }} >> .env
      #     echo PROJECT_ID=${{ secrets.PROJECT_ID }} >> .env
      #     echo REGION=${{ secrets.REGION }} >> .env
      #     echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
        


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Container Registry
        uses: docker/login-action@v1 
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_KEY_COBA }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_KEY_COBA }}
          export_default_credentials: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          no-cache: true
          tags: gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.SERVICE }} \
            --image gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.IMAGE_NAME }}:latest \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --service-account=848793158287-compute@developer.gserviceaccount.com