name: Build, Push, and Deploy to Cloud Run

on:
  push:
    branches:
      - main
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_KEY_COBA }}" > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
          gcloud config set project ${{ secrets.GCP_PROJECT }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY_COBA }}
      
      - name: Debug JSON File
        run: |
          ls -la /home/runner/work/coba-1/coba-1

      - name: Checkout repository
        uses: actions/checkout@v3
 
      # 2. Set up QEMU for multi-architecture builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Login to Google Container Registry
      - name: Login to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_KEY_COBA }}

      # 5. Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_VERSION }}
            gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_LATEST }}

      - name: Set Up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with: 
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_KEY_COBA }}

      # 7. Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.SERVICE }} \
              --image=gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.IMAGE_NAME }}:${{ secrets.TAG_LATEST }} \
              --allow-unauthenticated \
              --port=9000 \
              --service-account=1012925828272-compute@developer.gserviceaccount.com \
              --region=${{ secrets.REGION }} \
              --project=${{ secrets.GCP_PROJECT }}
